### ISSUE TITLE
use this plugin does it means didn't need use cross-tab-copy-paste plugin anymore ?

### ISSUE THREAD

**Issue by mlzboy** [mit-cml/workspace-multiselect#10]
blockly provider a plugin https://google.github.io/blockly-samples/plugins/cross-tab-copy-paste/README,could cross  workspace copy and paste,use workspace-multiselect seems also support cross workspace copy and paste ,dose it means did not need cross-tab-copy-paste plugin anymore?

**Comment by HollowMan6** [comment]
Yes! Since cross-tab-copy-paste causes a collision with this plugin, we just reimplemented it here in our plugin.

**Comment by mlzboy** [comment]
cool
