### ISSUE TITLE
share procedure copy and paste cross workspace feature

### ISSUE THREAD

**Issue by mlzboy** [mit-cml/workspace-multiselect#11]
Before use workspace-multiselect I used cross-copy-and-paste plugin and this plugin has something didn't finished. check `https://github.com/google/blockly/issues/6846` bellow is an example

![image](https://github.com/mit-cml/workspace-multiselect/assets/42778/c8ee8944-4ff9-4954-8f92-9b33ac61bdbe)

**Comment by HollowMan6** [comment]
Then let's wait for upstream to [fix the copy-pasting @blockly/block-sharable-procedures](https://github.com/google/blockly/issues/6846) before we check what we can do here to implement ours so that we can keep updated with upstream.

**Comment by HollowMan6** [comment]
Looks like blockly upstream chooses to upgrade the shareable procedures plugin and the blockly code instead of doing any changes to cross-copy-and-paste plugin https://github.com/google/blockly-samples/issues/1838 So this issue should be resolved when they roll out their updates.
