### ISSUE TITLE
Update to Blockly v10 support

### ISSUE THREAD

**Issue by ewpatton** [mit-cml/workspace-multiselect#12]
So there are at least two issues to worry about with the latest Blockly version

1. The block dragger stuff is supposedly going away.
2. Icons have been refactored, so right clicking on blocks is broken.

One of our new GSOC students also pointed out that there are phantom copies of blocks being created when they are dragged from the drawer when the multiselect plugin is enabled.

**Comment by HollowMan6** [comment]
That will be a headache if the block dragger is going away. This plugin will need a complete re-development to support v10 I think ...

**Comment by HollowMan6** [comment]
@ewpatton 

I just tried Blockly v10 with the multi-select plugin. The multi-block dragging is still working, I haven't checked the details, but at least we can keep the dragging stuff untouched when upgrading to v10.

The right-click is broken. We do need to re-work on this, I will fix that.

I'm not sure about phantom copies of blocks being created. At least from the UI side I don't see anything abnormal. Can he/she provide some detailed description / open a separate issue about that?

**Comment by HollowMan6** [comment]
Just checked the v10 change log in detail. It's actually a piece of great news instead that drag surfaces are finally removed: https://github.com/google/blockly/pull/7070 This plugin is built upon the fact that drag surfaces are disabled: https://github.com/mit-cml/workspace-multiselect/blob/c58bf7e4e730b6e9c5679f1378d750e6872dcb7a/src/multiselect_patch.js#L13-L19

Now this patch is no longer needed!

**Comment by HollowMan6** [comment]
> One of our new GSOC students also pointed out that there are phantom copies of blocks being created when they are dragged from the drawer when the multiselect plugin is enabled.

Fixed in: https://github.com/mit-cml/workspace-multiselect/pull/13/commits/f148ffb46255d93d3ad74d1d1fb35fce56e81b9f
