### ISSUE TITLE
Interacting with fields while shift held leaves shift state stuck

### ISSUE THREAD

**Issue by laurensvalk** [mit-cml/workspace-multiselect#16]
This is a really nice plugin! It should really help manage larger programs. I ran into a few minor issues experimenting with it. I submitted two small pull requests, but I wasn't sure about this one.

Interacting with fields while shift held leaves shift state stuck. To reproduce:

- First, press `shift` a few times to see it is properly working (see video)
- Select a few blocks
- While still holding `shift`, interact with a field. Here, I click on the repeat setting.
- Release `shift`
- The select state remains active, so any further interactions keep acting as selects even though shift was released.

https://github.com/mit-cml/workspace-multiselect/assets/12326241/8b10bcd3-1c38-4dcd-ab5c-19c12f483246

**Comment by laurensvalk** [comment]
Additional info: this appears to happen with Zelos, Thrasos and Geras.

**Comment by HollowMan6** [comment]
Haven't had time to check this in detail, but it looks like that, since you are editing the fields, the focus has shifted to the input field, then the plugin didn't catch the key release event. Maybe we should exit the multi-select mode as soon as we lost the focus.

**Comment by HollowMan6** [comment]
I will submit a PR to fix this when I have time.

**Comment by laurensvalk** [comment]
That was quick, thanks for looking into this! :smile:

**Comment by HollowMan6** [comment]
Will get fixed in the next release: https://github.com/mit-cml/workspace-multiselect/pull/19

See the commit reference above to see the exact commit for fixing this.
