### ISSUE TITLE
Interacting with ContextMenuRegistry

### ISSUE THREAD

**Issue by laurensvalk** [mit-cml/workspace-multiselect#17]
In the `cross-tab-copy-paste`  [usage instructions](https://github.com/google/blockly-samples/blob/master/plugins/cross-tab-copy-paste/README.md#usage) they suggest that you can hide the `duplicate` option. Similarly, I disable the inputs-inline option in our project as well:
```js
Blockly.ContextMenuRegistry.registry.unregister('blockDuplicate');
Blockly.ContextMenuRegistry.registry.unregister('blockInline');
```

I tried doing this also with the `workspace-multiselect` plugin, but this crashes with 
```
Menu item with ID "blockDuplicate" not found.
```
It does work if doing this after the plugin is initialized, but can then still crash on some interactions with the Blockly Playground when they trigger a reload.

Glancing at the code, it looks like this plugin manages the context menu in a different way. Is there a recommended way of doing it with this plugin?

Thanks!

**Comment by HollowMan6** [comment]
Will get fixed in the next release: https://github.com/mit-cml/workspace-multiselect/pull/19

No crash will happen either before or after the initialization when doing so.

See the commit reference above to see the exact commit for fixing this.

**Comment by laurensvalk** [comment]
Awesome, thank you! I look forward to trying all the fixes next week.
