### ISSUE TITLE
Selection can happen in different workspace

### ISSUE THREAD

**Issue by laurensvalk** [mit-cml/workspace-multiselect#18]
These are two separate blockly divs sitting side by side on one page.

The easiest way to reproduce seems to be to click the multi-select button to acivate, and then try to make selections in the other workspace.

https://github.com/mit-cml/workspace-multiselect/assets/12326241/97a4f773-562b-4364-82a3-4f328dab2c8d

From the outside, it seems somewhat similar to #16 

> (...) the focus has shifted to the input field, then the plugin didn't catch the key release event. Maybe we should exit the multi-select mode as soon as we lost the focus.

**Comment by HollowMan6** [comment]
Will get fixed in the next release: https://github.com/mit-cml/workspace-multiselect/pull/19

See the commit reference above to see the exact commit for fixing this.

multiple workspace tester for reference:
[test.zip](https://github.com/mit-cml/workspace-multiselect/files/12324496/test.zip)
