### ISSUE TITLE
Blocks with same ID get selected on all workspaces

### ISSUE THREAD

**Issue by laurensvalk** [mit-cml/workspace-multiselect#23]
This seems to happen with blocks with the same ID, e.g:
- blocks that are part of a default project which are the same across all projects (see first part of video)
- blocks copied from one workspace to another (see second part of video)

https://github.com/mit-cml/workspace-multiselect/assets/12326241/b3578854-a95d-4c7f-8b9c-63d5b836381e

**Comment by HollowMan6** [comment]
Unfortunately, I was aware of this issue already, as this is a side effect of https://github.com/mit-cml/workspace-multiselect/commit/9893cc401084e9e992e55d26503876297ad03c6c

**Comment by laurensvalk** [comment]
Thank you. I had disabled the extension for a while as I was working on other things (including modifying the `BlockDragger` for something unrelated). I am starting to put things back together now to see how it will go :slightly_smiling_face: 

The demo above is just a test project to preview multiple workspaces together. The actual app won't have it like this.

**Comment by HollowMan6** [comment]
PR opened at #24 . This should fix the issue
