### ISSUE TITLE
hideIcon: true still takes up space as if it is there

### ISSUE THREAD

**Issue by laurensvalk** [mit-cml/workspace-multiselect#27]
The icon seems to still take up space even when it is disabled:

`hideicon: false`

![image](https://github.com/mit-cml/workspace-multiselect/assets/12326241/e6b3d62d-2d4f-4c26-a92a-f66c816c926a)

`hideIcon: true`:

![image](https://github.com/mit-cml/workspace-multiselect/assets/12326241/c6d83126-2c63-437b-a7e9-4090aace7e88)

And the weight is also hardcoded.

-----

Possible API suggestion:

`showIcon: false`: don't show at all, and don't take space.

`showIcon: true` : show in default weight (3)

`showIcon: someNumber` like `true`, but weight set to given number.

**Comment by HollowMan6** [comment]
I don't like the idea of having both boolean and number type for config at the same time, we might go for TypeScript later, just like what Blockly is having.

So I added a new `weight` option there. Fixes available in #26

**Comment by laurensvalk** [comment]
Sure. Sounds good to me, thanks for looking into this so quickly!

(For what it's worth, a `boolean | number` type in Typescript is not uncommon.)

**Comment by HollowMan6** [comment]
> For what it's worth, a boolean | number type in Typescript is not uncommon.

At least it's kind of wired, anyway, I also don't want to break the current API by changing `hideIcon` to `showIcon`

**Comment by laurensvalk** [comment]
Confirmed with #26 that placement can now be selected:

![image](https://github.com/mit-cml/workspace-multiselect/assets/12326241/39803e0c-eb47-40d7-adc0-79a8a18c0e62)

as well as omitted

![image](https://github.com/mit-cml/workspace-multiselect/assets/12326241/81ddad4c-cd4e-4bad-8912-69726f40ce2e)
