### ISSUE TITLE
Conflict with Keyboard Navigation plugin

### ISSUE THREAD

**Issue by mark-friedman** [mit-cml/workspace-multiselect#41]
ICYMI, someone reported a conflict between the multi-select plugin and the keyboard navigation plugin in [this](https://groups.google.com/g/blockly/c/MuL2Ln8SwDU/m/Qsp71f2fAgAJ) Blockly group post.

> Then with the @mit-app-inventor/blockly-plugin-workspace-multiselect plugin which has the same 'copy' function name as the keyboard navigation plugin.

**Comment by HollowMan6** [comment]
I replied directly to the Blockly group post there (may take some time to show there). I guess this is related to the plugin initialization order, I tested and found that it works fine if the keyboard navigation plugin is initialized after the multi-select plugin. Anyway, we can keep the discussion there instead.

**Comment by mark-friedman** [comment]
> I replied directly to the Blockly group post ...
Yeah, I just wanted to make sure that you saw the post. 👍
