### ISSUE TITLE
this.draggedConnectionManager_ is undefined

### ISSUE THREAD

**Issue by SebCanet** [mit-cml/workspace-multiselect#42]
Hello,
when installing several plugins in my application, unless I've made some declaration errors, I've noticed that there are conflicts due to function names. With the @mit-app-inventor/blockly-plugin-workspace-multiselect plugin, which has the same 'copy' function name as the keyboard navigation plugin, I need to initialize the keyboard navigation plugin after the multi-select plugin, thanks ([https://groups.google.com/g/blockly/c/MuL2Ln8SwDU](https://groups.google.com/g/blockly/c/MuL2Ln8SwDU)) .

But if I select (keyboard shortcut or icon lick on workspace) it works and when I release by clicking group icon on workspace, here is the message:
this.draggedConnectionManager_ is undefined patchUpdateBlockAfterMove/this.BaseBlockDragger.prototype.updateBlockAfterMove_@webpack-internal:///./src/index.ts:9415:13 endDrag@webpack-internal:///./node_modules/blockly/blockly_compressed.js:1263:266 endDrag/<@webpack-internal:///./src/index.ts:9384:21 endDrag@webpack-internal:///./src/index.ts:9378:25 handleUp@webpack-internal:///./node_modules/blockly/blockly_compressed.js:667:212 f@webpack-internal:///./node_modules/blockly/blockly_compressed.js:84:159 EventListener.handleEvent*conditionalBind$$module$build$src$core$browser_events@webpack-internal:///./node_modules/blockly/blockly_compressed.js:84:393 bindMouseEvents@webpack-internal:///./node_modules/blockly/blockly_compressed.js:665:23 doStart@webpack-internal:///./node_modules/blockly/blockly_compressed.js:664:151 handleWsStart@webpack-internal:///./node_modules/blockly/blockly_compressed.js:673:8 wrappedFunc@webpack-internal:///./src/index.ts:9132:14 onMouseDown_@webpack-internal:///./node_modules/blockly/blockly_compressed.js:1089:428 f@webpack-internal:///./node_modules/blockly/blockly_compressed.js:84:149 

Thanks for your help.

**Comment by HollowMan6** [comment]
> I need to initialize the keyboard navigation plugin after the multi-select plugin, thanks (https://groups.google.com/g/blockly/c/MuL2Ln8SwDU)

Yes, I made that comment there.

> But if I select (keyboard shortcut or icon lick on workspace) it works and when I release by clicking group icon on workspace, here is the message:
this.draggedConnectionManager_ is undefined patchUpdateBlockAfterMove/this.BaseBlockDragger.prototype.updateBlockAfterMove_@webpack-internal:///./src/index.ts:9415:13 endDrag@webpack-internal:///./node_modules/blockly/blockly_compressed.js:1263:266 endDrag/<@webpack-internal:///./src/index.ts:9384:21 endDrag@webpack-internal:///./src/index.ts:9378:25 handleUp@webpack-internal:///./node_modules/blockly/blockly_compressed.js:667:212 f@webpack-internal:///./node_modules/blockly/blockly_compressed.js:84:159 EventListener.handleEvent*conditionalBind$$module$build$src$core$browser_events@webpack-internal:///./node_modules/blockly/blockly_compressed.js:84:393 bindMouseEvents@webpack-internal:///./node_modules/blockly/blockly_compressed.js:665:23 doStart@webpack-internal:///./node_modules/blockly/blockly_compressed.js:664:151 handleWsStart@webpack-internal:///./node_modules/blockly/blockly_compressed.js:673:8 wrappedFunc@webpack-internal:///./src/index.ts:9132:14 onMouseDown_@webpack-internal:///./node_modules/blockly/blockly_compressed.js:1089:428 f@webpack-internal:///./node_modules/blockly/blockly_compressed.js:84:149

Looks like our patch has been inferred by other code, not sure how this happen, but soon we are going to get rid of those monkey patches in Blockly 11 #39. Let's see how it goes then.
https://github.com/mit-cml/workspace-multiselect/blob/aafc9bcbda6f1f4763db76eba7d98856044ed136/src/multiselect_block_dragger.js#L152-L176

**Comment by HollowMan6** [comment]
Okay, looks like they have deprecated insertion marker https://github.com/google/blockly/pull/7797

**Comment by HollowMan6** [comment]
Okay, so basically we do not support blockly 10.4.0+ due to https://github.com/google/blockly/commit/0b344e7fab3ba50eaf7e288ece5d6f5036388c19 I will update PR #38 to get it supported.

**Comment by HollowMan6** [comment]
Now `this.draggedConnectionManager_ is undefined` is fixed in #38. We will release that into v0.1.12, try that out now if you like.
